const fs = require("fs");
const path = require("path");
const { setState, STATE_PAIRED } = require("../identity");
const { subjectsForDevice } = require("../device-nats");

const APP_DIR = process.platform === "darwin" || process.platform === "win32" ?
    path.join(process.cwd(), ".vetura-agent-runtime") : "/opt/vetura-agent";
const CREDS_FILE = path.join(APP_DIR, "credentials.creds");
const ENV_FILE = path.join(APP_DIR, ".env");

const DEFAULTS = {
    NATS_URL: "tls://nats.mnq.nl-ams.scaleway.com:4222",
    NATS_STREAM: "commands",
    NATS_MAX_AGE_SEC: "900",
};

function escapeEnvValue(value) {
    const str = String(value);
    if (/[\s#"'$\\]/.test(str)) {
        return `"${str.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
    }
    return str;
}

function buildEnvContents(config) {
    const lines = [
        `# Generated by vetura-agent setup at ${new Date().toISOString()}`,
        `NATS_URL=${escapeEnvValue(config.natsUrl)}`,
        `NATS_CREDS_FILE=${escapeEnvValue(config.credsFile || CREDS_FILE)}`,
        `NATS_STREAM=${escapeEnvValue(config.stream || DEFAULTS.NATS_STREAM)}`,
        `NATS_SUBJECT=${escapeEnvValue(config.subject)}`,
        `NATS_ERROR_SUBJECT=${escapeEnvValue(config.errorSubject)}`,
        `NATS_RESULT_SUBJECT=${escapeEnvValue(config.resultSubject)}`,
        `NATS_CONSUMER=${escapeEnvValue(config.consumer)}`,
        `NATS_MAX_AGE_SEC=${escapeEnvValue(
            config.maxAgeSec != null
                ? config.maxAgeSec
                : DEFAULTS.NATS_MAX_AGE_SEC,
        )}`,
    ];
    return `${lines.join("\n")}\n`;
}

function validateConfig(input) {
    const errors = [];
    const creds = String(input.credsFileContents || "").trim();
    if (!creds.includes("-----BEGIN")) {
        errors.push("Credentials must be a Scaleway NATS .creds file");
    }

    const natsUrl = String(input.natsUrl || "").trim();
    if (!natsUrl) errors.push("NATS_URL is required");

    const subject = String(input.subject || "").trim();
    if (!subject) errors.push("NATS_SUBJECT is required");

    const errorSubject = String(input.errorSubject || "").trim();
    if (!errorSubject) errors.push("NATS_ERROR_SUBJECT is required");

    const resultSubject = String(input.resultSubject || "").trim();
    if (!resultSubject) errors.push("NATS_RESULT_SUBJECT is required");

    const consumer = String(input.consumer || "").trim();
    if (!consumer) errors.push("NATS_CONSUMER is required");

    if (errors.length) {
        return { ok: false, errors };
    }

    return {
        ok: true,
        config: {
            natsUrl,
            stream: String(input.stream || DEFAULTS.NATS_STREAM).trim(),
            subject,
            errorSubject,
            resultSubject,
            consumer,
            maxAgeSec:
                input.maxAgeSec != null && String(input.maxAgeSec).trim() !== ""
                    ? String(input.maxAgeSec).trim()
                    : DEFAULTS.NATS_MAX_AGE_SEC,
            credsFileContents: creds,
            credsFile: CREDS_FILE,
        },
    };
}

function configFromBootstrap(payload, deviceId) {
    const names = subjectsForDevice(deviceId);
    return validateConfig({
        natsUrl: payload.natsUrl || DEFAULTS.NATS_URL,
        stream: payload.stream || names.stream,
        subject: payload.subject || names.subject,
        errorSubject: payload.errorSubject || names.errorSubject,
        resultSubject: payload.resultSubject || names.resultSubject,
        consumer: payload.consumer || names.consumer,
        maxAgeSec: payload.maxAgeSec,
        credsFileContents: payload.credsFileContents,
    });
}

// Temp file + fsync + rename: a power cut must never leave these files empty.
function writeFileAtomic(file, contents) {
    const tmp = `${file}.${process.pid}.tmp`;
    const fd = fs.openSync(tmp, "w", 0o600);
    try {
        fs.writeFileSync(fd, contents);
        fs.fsyncSync(fd);
    } finally {
        fs.closeSync(fd);
    }
    fs.renameSync(tmp, file);
}

function writeFiles(config) {
    fs.mkdirSync(path.dirname(CREDS_FILE), { recursive: true });
    fs.mkdirSync(APP_DIR, { recursive: true });
    writeFileAtomic(CREDS_FILE, `${config.credsFileContents.trim()}\n`);
    writeFileAtomic(ENV_FILE, buildEnvContents(config));
}

function applyPairing(input) {
    const validated = input && input.ok === true && input.config
        ? input
        : validateConfig(input);

    if (!validated.ok) {
        return { ok: false, errors: validated.errors };
    }

    writeFiles(validated.config);
    setState(STATE_PAIRED);

    return {
        ok: true,
        config: {
            natsUrl: validated.config.natsUrl,
            stream: validated.config.stream,
            subject: validated.config.subject,
            errorSubject: validated.config.errorSubject,
            resultSubject: validated.config.resultSubject,
            consumer: validated.config.consumer,
            credsFile: validated.config.credsFile,
        },
    };
}

module.exports = {
    configFromBootstrap,
    applyPairing,
};
