#!/bin/sh
# initramfs-tools hook: cryptsetup, e2fsprogs, rpi-fw-crypto, LUKS keyscript.
PREREQ=""
prereqs() { echo "${PREREQ}"; }
case "${1:-}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/cryptsetup
copy_exec /sbin/resize2fs
copy_exec /sbin/e2fsck
copy_exec /sbin/dumpe2fs
copy_exec /sbin/blkid
if [ -x /usr/sbin/reboot ]; then
	copy_exec /usr/sbin/reboot
elif [ -x /sbin/reboot ]; then
	copy_exec /sbin/reboot
fi
if [ -x /usr/bin/rpi-fw-crypto ]; then
	copy_exec /usr/bin/rpi-fw-crypto
elif [ -x /usr/sbin/rpi-fw-crypto ]; then
	copy_exec /usr/sbin/rpi-fw-crypto
fi
copy_exec /usr/lib/dkgm/luks-key

# Firmware crypto mailbox (name varies by kernel).
for node in /lib/udev/rules.d/*vcio* /lib/udev/rules.d/*fw-crypto*; do
	[ -f "${node}" ] && copy_file udev "${node}"
done
