Section "ServerFlags"
	Option "BlankTime" "0"
	Option "StandbyTime" "0"
	Option "SuspendTime" "0"
	Option "OffTime" "0"
	Option "AutoAddGPU" "false"
EndSection

Section "Device"
	Identifier "vetura-fb"
	Driver "fbdev"
	Option "fbdev" "/dev/fb0"
EndSection
